// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vpcYHrXbsH6LUnbKFzgKAs
// Component: 7MQ1w3J5JA
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_abc_framework.module.css"; // plasmic-import: vpcYHrXbsH6LUnbKFzgKAs/projectcss
import * as sty from "./PlasmicActionIcon.module.css"; // plasmic-import: 7MQ1w3J5JA/css

export const PlasmicActionIcon__VariantProps = new Array("large", "extraLarge");

export const PlasmicActionIcon__ArgProps = new Array("children");

function PlasmicActionIcon__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__extraLarge]: hasVariant(
          variants,
          "extraLarge",
          "extraLarge"
        ),

        [sty.root__large]: hasVariant(variants, "large", "large")
      })}
    >
      <p.PlasmicSlot
        defaultContents={"I"}
        value={args.children}
        className={classNames(sty.slotChildren, {
          [sty.slotChildren__extraLarge]: hasVariant(
            variants,
            "extraLarge",
            "extraLarge"
          ),

          [sty.slotChildren__large]: hasVariant(variants, "large", "large")
        })}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicActionIcon__ArgProps,
      internalVariantPropNames: PlasmicActionIcon__VariantProps
    });

    return PlasmicActionIcon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicActionIcon";
  } else {
    func.displayName = `PlasmicActionIcon.${nodeName}`;
  }
  return func;
}

export const PlasmicActionIcon = Object.assign(
  // Top-level PlasmicActionIcon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicActionIcon
    internalVariantProps: PlasmicActionIcon__VariantProps,
    internalArgProps: PlasmicActionIcon__ArgProps
  }
);

export default PlasmicActionIcon;
/* prettier-ignore-end */
