// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vpcYHrXbsH6LUnbKFzgKAs
// Component: MBa3bpDzoK
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_abc_framework.module.css"; // plasmic-import: vpcYHrXbsH6LUnbKFzgKAs/projectcss
import * as sty from "./PlasmicLabeledBox.module.css"; // plasmic-import: MBa3bpDzoK/css

export const PlasmicLabeledBox__VariantProps = new Array();

export const PlasmicLabeledBox__ArgProps = new Array("area", "label");

function PlasmicLabeledBox__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicSlot
        defaultContents={"Label"}
        value={args.label}
        className={classNames(sty.slotLabel)}
      />

      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        <p.PlasmicSlot defaultContents={null} value={args.area} />
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLabeledBox__ArgProps,
      internalVariantPropNames: PlasmicLabeledBox__VariantProps
    });

    return PlasmicLabeledBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLabeledBox";
  } else {
    func.displayName = `PlasmicLabeledBox.${nodeName}`;
  }
  return func;
}

export const PlasmicLabeledBox = Object.assign(
  // Top-level PlasmicLabeledBox renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicLabeledBox
    internalVariantProps: PlasmicLabeledBox__VariantProps,
    internalArgProps: PlasmicLabeledBox__ArgProps
  }
);

export default PlasmicLabeledBox;
/* prettier-ignore-end */
