// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vpcYHrXbsH6LUnbKFzgKAs
// Component: 08Del2QF4A
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_abc_framework.module.css"; // plasmic-import: vpcYHrXbsH6LUnbKFzgKAs/projectcss
import * as sty from "./PlasmicColumnSpacer.module.css"; // plasmic-import: 08Del2QF4A/css

export const PlasmicColumnSpacer__VariantProps = new Array();

export const PlasmicColumnSpacer__ArgProps = new Array();

function PlasmicColumnSpacer__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  null;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicColumnSpacer__ArgProps,
      internalVariantPropNames: PlasmicColumnSpacer__VariantProps
    });

    return PlasmicColumnSpacer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicColumnSpacer";
  } else {
    func.displayName = `PlasmicColumnSpacer.${nodeName}`;
  }
  return func;
}

export const PlasmicColumnSpacer = Object.assign(
  // Top-level PlasmicColumnSpacer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicColumnSpacer
    internalVariantProps: PlasmicColumnSpacer__VariantProps,
    internalArgProps: PlasmicColumnSpacer__ArgProps
  }
);

export default PlasmicColumnSpacer;
/* prettier-ignore-end */
