// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vpcYHrXbsH6LUnbKFzgKAs
// Component: wpvaXd42G3
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_abc_framework.module.css"; // plasmic-import: vpcYHrXbsH6LUnbKFzgKAs/projectcss
import * as sty from "./PlasmicResearchCard.module.css"; // plasmic-import: wpvaXd42G3/css

export const PlasmicResearchCard__VariantProps = new Array();

export const PlasmicResearchCard__ArgProps = new Array(
  "title",
  "description",
  "link",
  "method"
);

function PlasmicResearchCard__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  null;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.PlasmicSlot
        defaultContents={"Pesquisa #1"}
        value={args.title}
        className={classNames(sty.slotTitle)}
      />

      <p.PlasmicSlot
        defaultContents={"Pesquisa sobre bla bla bla bla bla"}
        value={args.description}
        className={classNames(sty.slotDescription)}
      />

      <p.PlasmicSlot
        defaultContents={"Link: link.com"}
        value={args.link}
        className={classNames(sty.slotLink)}
      />

      <p.PlasmicSlot
        defaultContents={"Método: b"}
        value={args.method}
        className={classNames(sty.slotMethod)}
      />
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicResearchCard__ArgProps,
      internalVariantPropNames: PlasmicResearchCard__VariantProps
    });

    return PlasmicResearchCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicResearchCard";
  } else {
    func.displayName = `PlasmicResearchCard.${nodeName}`;
  }
  return func;
}

export const PlasmicResearchCard = Object.assign(
  // Top-level PlasmicResearchCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicResearchCard
    internalVariantProps: PlasmicResearchCard__VariantProps,
    internalArgProps: PlasmicResearchCard__ArgProps
  }
);

export default PlasmicResearchCard;
/* prettier-ignore-end */
