// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import { PlasmicHeader } from "./plasmic/abc_framework/PlasmicHeader";

import { useSelector, useDispatch } from "react-redux";
import { getUser } from "../store/auth/selectors";
import { logout } from "../store/auth/actions";
import { GoogleLogout } from "react-google-login";
import { GOOGLE_CLIENT_ID } from "../constants";
import useHistory from "../useHistory";

function Header(props) {

  const history = useHistory();
  const dispatch = useDispatch();

  const [showUserOptions, setShowUserOptions] = useState(false);
  const user = useSelector(getUser);

  const onSuccessfulResponse = () => {
    dispatch(logout());
  };

  return (
    <PlasmicHeader 
      {...props}
      withUserOptions={showUserOptions}
      logoAreaContainer={{
        props: {
          onClick: () => {
            history.push(`/dashboard`);
          },
        }
      }}
      tutorial={{
        button: {
          onClick: () => {
            history.push(`/tutorial`);
          },
        },
      }}
      userPic={{
        props: {
          onClick: () => {
            setShowUserOptions(c => !c);
          },
          children: [
            (
              <img
                key={"profile-picture"}
                src={user.picture}
                width={"100%"}
                height={"100%"}
                alt="Imagem de perfil"
                style={{ borderRadius: "100%", }}
              />
            )
          ],
        },
      }}
      options={
        [
          <GoogleLogout
            key={"google-logout"}
            clientId={GOOGLE_CLIENT_ID}
            onLogoutSuccess={onSuccessfulResponse}
            render={(p) => {
              return (
                <div style={{
                  display: "flex",
                  cursor: "pointer",
                }}
                  onClick={p.onClick}
                >
                  <p style={{ color: "white"}}>Sair</p>
                </div>
              )
            }}
          />
        ]
      }
    />
  );
}

export default Header;
