// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { GoogleLogin } from "react-google-login";
import { useDispatch } from "react-redux";

import { PlasmicHomepage } from "./plasmic/abc_framework/PlasmicHomepage";

import { GOOGLE_CLIENT_ID } from "../constants";
import { login } from "../store/auth/actions";

function Homepage() {
  const dispatch = useDispatch();
  const onSuccessfulResponse = (response) => {
    const { tokenId } = response;
    dispatch(login(tokenId));
  };

  return (
    <PlasmicHomepage loginOptions={
      [
        <GoogleLogin
          key="google-login"
          clientId={GOOGLE_CLIENT_ID}
          onSuccess={onSuccessfulResponse}
          buttonText={'Entrar com conta Google'}
          cookiePolicy={'single_host_origin'}
          isSignedIn={true}
        />
      ]
    }/>
  );
}

export default Homepage;
