// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import { PlasmicQuestion } from "./plasmic/abc_framework/PlasmicQuestion";

function Question(props) {
  const [isClosed, setIsClosed] = useState(false);
  return (
    <PlasmicQuestion
      isClosed={isClosed}
      icon={{
        onClick: () => setIsClosed(c => !c),
      }}
      {...props}
    />
  );
}

export default Question;
