// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { editResearch } from "../store/programs/actions";
import { getResearch } from "../store/programs/selectors";
import { PlasmicResearchCard } from "./plasmic/abc_framework/PlasmicResearchCard";

function ResearchCard(props) {
  const dispatch = useDispatch();

  const { researchProgramId, researchId, ...rest } = props;

  const research = useSelector(getResearch(researchProgramId, researchId));
  
  const [isEditing, setIsEditing] = useState(false);
  const [researchEdit, setResearchEdit] = useState(research);

  return (
    <PlasmicResearchCard
      withEdit={isEditing}
      edit={{
        onClick: () => setIsEditing(true),
      }}
      titleInput={{
        textbox: {
          value: researchEdit.title,
          onChange: (e) => setResearchEdit(r => ({ ...r, title: e.target.value })),
        },
      }}
      descriptionInput={{
        textarea: {
          value: researchEdit.description,
          onChange: (e) => setResearchEdit(r => ({ ...r, description: e.target.value })),
        },
      }}
      linkInput={{
        textbox: {
          value: researchEdit.link,
          onChange: (e) => setResearchEdit(r => ({ ...r, link: e.target.value })),
        },
      }}
      saveBtn={{
        button: {
          onClick: () => {
            dispatch(editResearch(researchProgramId, researchId, researchEdit));
            setIsEditing(false);
          },
        },
      }}
      cancelBtn={{
        button: {
          onClick: () => setIsEditing(false),
        },
      }}
      {...rest} 
    />
  );
}

export default ResearchCard;
