// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useParams } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import { PlasmicSelectedStrategyResearches } from "./plasmic/abc_framework/PlasmicSelectedStrategyResearches";

import { getSelectedStrategy } from "../store/selectedStrategy/selectors";
import { getResearches } from "../store/programs/selectors";
import ResearchCard from "./ResearchCard";
import { deleteResearch } from "../store/programs/actions";

function SelectedStrategyResearches() {
  const dispatch = useDispatch();
  const { id } = useParams();
  const strategy = useSelector(getSelectedStrategy);
  const researches = useSelector(getResearches(id, strategy));

  return (
    <PlasmicSelectedStrategyResearches 
      empty={researches.length === 0}
      researches={
        researches.map((research) => (
          <ResearchCard
            key={research._id}
            title={research.title}
            description={research.description}
            method={`Método: ${research.method}`}
            link={`Link: ${research.link}`}
            _delete={{
              onClick: () => {
                dispatch(deleteResearch(id, research._id));
              }
            }}
          />
        ))
      }
    />
  );
}

export default SelectedStrategyResearches;
