// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useParams, useDispatch } from "react-router-dom";
import { useSelector } from "react-redux";
import { PlasmicSelectedResearch } from "./plasmic/abc_framework/PlasmicSelectedResearch";
import { getResearchProgram } from "../store/programs/selectors";
import { deleteResearchProgram } from "../store/programs/actions";

function SelectedResearch() {
  const dispatch = useDispatch();
  const { id } = useParams();
  const program = useSelector(getResearchProgram(id));
  const isLoading = !program;
  return (
    <PlasmicSelectedResearch
      title={isLoading ? "Carregando" : program.title}
      description={isLoading ? "Carregando" : program.description}
      _delete={{
        onClick: () => {
          dispatch(deleteResearchProgram(id));
        }
      }}
    />
  );
}

export default SelectedResearch;
