// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import { useParams } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import { PlasmicSelectedResearch } from "./plasmic/abc_framework/PlasmicSelectedResearch";
import { getResearchProgram } from "../store/programs/selectors";
import { editResearchProgram } from "../store/programs/actions";

function SelectedResearch(props) {
  const dispatch = useDispatch();

  const { id } = useParams();
  const program = useSelector(getResearchProgram(id));

  const [isEditing, setIsEditing] = useState(false);
  const [editProgram, setEditProgram] = useState(program);

  const isLoading = !program;
  return (
    <PlasmicSelectedResearch
      title={isLoading ? "Carregando" : program.title}
      description={isLoading ? "Carregando" : program.description}
      withEdit={isEditing}
      edit={{
        onClick: () => setIsEditing(true),
      }}
      titleInput={{
        textbox: {
          value: editProgram.title,
          onChange: (e) => setEditProgram(r => ({ ...r, title: e.target.value })),
        },
      }}
      descriptionInput={{
        textarea: {
          value: editProgram.description,
          onChange: (e) => setEditProgram(r => ({ ...r, description: e.target.value }))
        }
      }}
      saveBtn={{
        button: {
          onClick: () => {
            dispatch(editResearchProgram(id, editProgram));
            setIsEditing(false);
          },
        },
      }}
      cancelBtn={{
        button: {
          onClick: () => {
            setIsEditing(false);
          },
        },
      }}
      {...props}
    />
  );
}

export default SelectedResearch;
