// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { useSelector } from "react-redux";
import { PlasmicSelectedStrategy } from "./plasmic/abc_framework/PlasmicSelectedStrategy";

import { getSelectedStrategy } from "../store/selectedStrategy/selectors";
import { selectedStrategyDescription, selectedStrategyTitle } from "../constants";

function SelectedStrategy() {
  const strategy = useSelector(getSelectedStrategy);

  return (
    <PlasmicSelectedStrategy 
      empty={!strategy}
      title={strategy ? selectedStrategyTitle[strategy] : "Nenhuma estratégia selecionada"}
      description={strategy ? selectedStrategyDescription[strategy] : ""}
    />
  );
}

export default SelectedStrategy;
